// pages/api/webhook.ts
import { Webhooks } from '@octokit/webhooks';
import { IncomingMessage, ServerResponse } from 'http';
import axios from 'axios';

const webhooks = new Webhooks({
  secret: process.env.WEBHOOK_SECRET || '',
});

// AI Review Prompt Template
const AI_PROMPT_TEMPLATE = `
As a senior software engineer with 15+ years of experience, review this pull request thoroughly.

**Pull Request Title**: {PR_TITLE}
**Repository**: {REPO_NAME}
**Author**: {PR_AUTHOR}

**Review Guidelines**:
1. Code Quality: Check for clean, maintainable code with proper structure
2. Logic Errors: Identify potential bugs or flawed logic
3. Security: Flag any security vulnerabilities (SQLi, XSS, auth issues, etc.)
4. Performance: Suggest performance optimizations
5. Best Practices: Ensure adherence to language/framework best practices
6. Readability: Check for proper naming, comments, and documentation
7. Testing: Verify adequate test coverage where applicable

**Code Changes**:
\`\`\`diff
{PR_DIFF}
\`\`\`

**Provide your review**:
- Use markdown formatting
- Be constructive and professional
- Group feedback by category (Critical, Suggestions, Nitpicks)
- Include code examples for improvements
- Keep it concise but thorough
- Highlight any blockers that should prevent merging

**Review Output**:`;

webhooks.on('pull_request.opened', async ({ payload }) => {
  const { pull_request, repository } = payload;
  console.log(`Processing PR #${pull_request.number} in ${repository.full_name}`);

  try {
    // Get PR details
    const diffResponse = await axios.get(pull_request.diff_url);
    const diff = diffResponse.data;

    // Generate AI review
    const prompt = AI_PROMPT_TEMPLATE
      .replace('{PR_TITLE}', pull_request.title)
      .replace('{REPO_NAME}', repository.full_name)
      .replace('{PR_AUTHOR}', pull_request.user.login)
      .replace('{PR_DIFF}', diff);

    const review = await generateAIReview(prompt);

    // Post comment to PR
    await postPRComment(
      repository.owner.login,
      repository.name,
      pull_request.number,
      review
    );

    console.log(`Successfully reviewed PR #${pull_request.number}`);

    console.log('=== NEW WEBHOOK RECEIVED ===');
console.log('Repository:', payload.repository?.full_name);
console.log('PR Number:', payload.pull_request?.number);

// After getting the diff
console.log('Diff length:', diff.length);

// After AI response
console.log('AI Response:', review);

// After posting comment
console.log('Comment posted successfully');

  } catch (error) {
    console.error(`Error processing PR #${pull_request.number}:`, error);
  }
});

async function generateAIReview(prompt: string): Promise<string> {
  try {
    const response = await axios.post(
      'https://api.together.xyz/inference',
      {
        model: 'togethercomputer/CodeLlama-13b-Instruct',
        prompt,
        max_tokens: 1500,
        temperature: 0.7,
        top_p: 0.7,
        top_k: 50,
        repetition_penalty: 1.1,
        stop: ['</s>', '###']
      },
      {
        headers: {
          'Authorization': `Bearer ${process.env.TOGETHER_API_KEY}`,
          'Content-Type': 'application/json',
        },
        timeout: 30000
      }
    );

    return response.data?.output?.choices?.[0]?.text || 'No review generated';
  } catch (error:any) {
    console.error('AI Review Error:', error);
    return `⚠️ Unable to generate full review due to an error. Partial response:\n\n${
      error.response?.data?.error?.message || 'Please try again later.' 
    }`;
  }
}

async function postPRComment(
  owner: string,
  repo: string,
  prNumber: number,
  body: string
) {
  const { Octokit } = require('@octokit/core');
  const { createAppAuth } = require('@octokit/auth-app');

  const octokit = new Octokit({
    authStrategy: createAppAuth,
    auth: {
      appId: process.env.GITHUB_APP_ID,
      privateKey: process.env.GITHUB_PRIVATE_KEY?.replace(/\\n/g, '\n'),
    },
  });

  try {
    // Get installation ID
    const { data: installation } = await octokit.request(
      'GET /repos/{owner}/{repo}/installation',
      { owner, repo }
    );

    // Authenticate as installation
    const installationOctokit = new Octokit({
      auth: installation.token,
    });

    // Post comment
    await installationOctokit.request(
      'POST /repos/{owner}/{repo}/issues/{issue_number}/comments',
      {
        owner,
        repo,
        issue_number: prNumber,
        body: `## 🤖 NexGenGit AI Review\n\n${body}\n\n*This review was automatically generated by [NexGenGit](${process.env.NEXTAUTH_URL})*`,
      }
    );
  } catch (error) {
    console.error('GitHub API Error:', error);
    throw error;
  }
}

export default function handler(req: IncomingMessage, res: ServerResponse) {
  if (req.method === 'POST') {
    let body = '';
    req.on('data', (chunk) => (body += chunk));
    req.on('end', () => {
      const headers = req.headers;
      webhooks
        .verifyAndReceive({
          id: headers['x-github-delivery'] as string,
          name: headers['x-github-event'] as string,
          payload: body,
          signature: headers['x-hub-signature-256'] as string,
        })
        .then(() => {
          res.statusCode = 200;
          res.end('Webhook processed');
        })
        .catch((err) => {
          console.error('Webhook error:', err);
          res.statusCode = 500;
          res.end('Webhook error');
        });
    });
  } else {
    res.statusCode = 404;
    res.end('Not found');
  }
}

export const config = {
  api: {
    bodyParser: false,
  },
};